" .vimrc
" Author: Justin Mayer (@jmayer)
" Source: https://bitbucket.org/j/dotfiles/src/tip/vim/

set nocompatible          " Use vim instead of vi settings; this must come first

source ~/.vim/vundle.vim  " Plugins contained within are installed via Vundle

filetype plugin indent on " Load filetype-specific indent and plugin files

source ~/.vim/config.vim  " Core configuration
source ~/.vim/keys.vim    " Keys and bindings
source ~/.vim/plugins.vim " Plugin-specific configuration
